[2022-07-08 05:28:23,203] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_dag5.local_to_gcs_task scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-07-08 05:28:26,126] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: yellow_taxi_dag5.local_to_gcs_task scheduled__2020-04-02T06:00:00+00:00 [queued]>
[2022-07-08 05:28:26,137] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 05:28:26,139] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-07-08 05:28:26,143] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-08 05:28:27,333] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-04-02 06:00:00+00:00
[2022-07-08 05:28:27,581] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'yellow_taxi_dag5', 'local_to_gcs_task', 'scheduled__2020-04-02T06:00:00+00:00', '--job-id', '306', '--raw', '--subdir', 'DAGS_FOLDER/yellow_taxi_dag.py', '--cfg-path', '/tmp/tmpxf15d2dc', '--error-file', '/tmp/tmpolrj2woi']
[2022-07-08 05:28:27,639] {standard_task_runner.py:77} INFO - Job 306: Subtask local_to_gcs_task
[2022-07-08 05:28:27,554] {standard_task_runner.py:52} INFO - Started process 2570 to run task
[2022-07-08 05:28:29,001] {logging_mixin.py:109} INFO - Running <TaskInstance: yellow_taxi_dag5.local_to_gcs_task scheduled__2020-04-02T06:00:00+00:00 [running]> on host 2b856f2081be
[2022-07-08 05:28:31,033] {warnings.py:99} WARNING - /home/***/.local/lib/python3.6/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-07-08 05:28:31,936] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=yellow_taxi_dag5
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-04-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-04-02T06:00:00+00:00
[2022-07-08 05:28:31,950] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_taxi_dag.py", line 36, in upload_to_gcs
    storage.blob._MAX_MULTIPART_SIZE = 5 * 1024 * 1024  # 5 MB
NameError: name 'storage' is not defined
[2022-07-08 05:28:32,458] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=yellow_taxi_dag5, task_id=local_to_gcs_task, execution_date=20200402T060000, start_date=20220708T052823, end_date=20220708T052832
[2022-07-08 05:28:33,895] {standard_task_runner.py:92} ERROR - Failed to execute job 306 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/yellow_taxi_dag.py", line 36, in upload_to_gcs
    storage.blob._MAX_MULTIPART_SIZE = 5 * 1024 * 1024  # 5 MB
NameError: name 'storage' is not defined
[2022-07-08 05:28:36,272] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-08 05:28:45,416] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
