[2022-07-07 21:32:51,322] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_full_yt.local_to_gcs_task scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-07-07 21:32:51,339] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_full_yt.local_to_gcs_task scheduled__2022-06-02T06:00:00+00:00 [queued]>
[2022-07-07 21:32:51,340] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 21:32:51,341] {taskinstance.py:1239} INFO - Starting attempt 3 of 4
[2022-07-07 21:32:51,342] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-07-07 21:32:51,355] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2022-06-02 06:00:00+00:00
[2022-07-07 21:32:51,362] {standard_task_runner.py:52} INFO - Started process 3068 to run task
[2022-07-07 21:32:51,366] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_full_yt', 'local_to_gcs_task', 'scheduled__2022-06-02T06:00:00+00:00', '--job-id', '122', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_full_yt.py', '--cfg-path', '/tmp/tmpcj_rzh67', '--error-file', '/tmp/tmp3um1ju_k']
[2022-07-07 21:32:51,371] {standard_task_runner.py:77} INFO - Job 122: Subtask local_to_gcs_task
[2022-07-07 21:32:51,440] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_full_yt.local_to_gcs_task scheduled__2022-06-02T06:00:00+00:00 [running]> on host 2b856f2081be
[2022-07-07 21:32:51,499] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_full_yt
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2022-06-02T06:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-02T06:00:00+00:00
[2022-07-07 21:32:51,523] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_full_yt.py", line 66, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_42.parquet'
[2022-07-07 21:32:51,548] {taskinstance.py:1277} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcs_full_yt, task_id=local_to_gcs_task, execution_date=20220602T060000, start_date=20220707T213251, end_date=20220707T213251
[2022-07-07 21:32:51,562] {standard_task_runner.py:92} ERROR - Failed to execute job 122 for task local_to_gcs_task
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/data_ingestion_gcs_full_yt.py", line 66, in upload_to_gcs
    blob.upload_from_filename(local_file)
  File "/home/airflow/.local/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 2720, in upload_from_filename
    with open(filename, "rb") as file_obj:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/output_42.parquet'
[2022-07-07 21:32:51,592] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-07-07 21:32:51,627] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
